#include "entity/mesh/mesh_parser.h"
#include "entity/mesh/e_tetrahedron.h"
#include "entity/mesh/e_triangle.h"

#include <map>
#include <algorithm>
#include <filesystem>



Mesh_Parser::Mesh_Parser(Mesh_Format format):format_(format)
{

}

Type convert_Type(int gmsh_type) {
    switch (gmsh_type) {
        case 1:  return Type::EDGE;        // 2-node line
        case 2:  return Type::TRIANGLE;    // 3-node triangle
        case 4:  return Type::TETRAHEDRON; // 4-node tetrahedron
        case 15: return Type::NODE;        // 1-node point
        default:
            // Handle unsupported shapes (Quads, Hexahedra, etc.)
            throw std::invalid_argument("Unsupported Gmsh element type: " + std::to_string(gmsh_type));
    }
}



Mesh Mesh_Parser::load_mesh(const std::string& filename)
{
    std::string ext = std::filesystem::path(filename).extension().string();
    switch (format_) {
        case Mesh_Format::GMSH:
            if (ext == ".msh" || ext == ".geo")
            {
                return load_gmsh(filename);
            } else {
                throw std::runtime_error("Error: Gmsh does not support " + ext + " format for file: " + filename);
            }
        default:
            throw std::runtime_error("Mesh format " + ext + " is not supported yet.");;
    }
}


std::vector<size_t> Mesh_Parser::build_tag_to_index_map(const std::vector<size_t>& node_tags)
{
    size_t max_tag = 0;
    for (auto t : node_tags)
        if (t > max_tag) max_tag = t;

    std::vector<size_t> map(max_tag + 1, static_cast<size_t>(-1));
    for (size_t i = 0; i < node_tags.size(); ++i)
        map[node_tags[i]] = i;

    return map;
}

Element* Mesh_Parser::create_element(int gmsh_type,
                                    const size_t* node_indices,
                                    size_t property_id)
{
    switch (gmsh_type) {
        case 4:  return new Tetrahedron(node_indices, property_id);
        // case 2:  return new Triangle(node_indices, property_id);
        // case 1:  return new Edge(node_indices, property_id);
        // case 15: return new NodeElement(node_indices, property_id);
        default: return nullptr;
    }
}


Mesh Mesh_Parser::load_gmsh(const std::string& filename)
{
#ifdef LOAD_GMSH
    gmsh::initialize();
    gmsh::option::setNumber("General.Verbosity", 1);
    gmsh::open(filename);

    Logger::info("Load mesh: " + filename);

    Mesh mesh;
    mesh.dim_ = gmsh::model::getDimension();

    // ---- Nodes ----
    std::vector<size_t> node_tags;
    std::vector<double> coords;
    std::vector<double> parametric; // unused

    //gmsh::model::mesh::generate(mesh.dim_);
    gmsh::model::mesh::getNodes(node_tags, coords, parametric);
    mesh.n_node = node_tags.size();

    //auto tag_to_idx = build_tag_to_index_map(node_tags);

    // Store node coordinates indexed by 0-based index.
    // Gmsh returns nodes in node_tags order, which may not be contiguous,
    // so we use the tag_to_idx mapping.
    mesh.nodes.resize(mesh.n_node);
    for (size_t i = 0; i < node_tags.size(); ++i) {
        //size_t idx = tag_to_idx[node_tags[i]];
        mesh.nodes[node_tags[i]-1].x = coords[3 * i];
        mesh.nodes[node_tags[i]-1].y = coords[3 * i + 1];
        mesh.nodes[node_tags[i]-1].z = coords[3 * i + 2];
    }

    // create key of element groups generated by gmsh file
    gmsh::vectorpair                   physicalGroups_dim_tag;
    std::map<std::pair<int, int>, Key> physicalGroups_to_key;
    gmsh::model::getPhysicalGroups(physicalGroups_dim_tag);

    Logger::info("Node number: " + std::to_string(mesh.n_node));


    Logger::info("Physical groups: Load elements...");
    for(std::pair<int,int> &dim_tag : physicalGroups_dim_tag){
        uint32_t dim = static_cast<uint32_t>(dim_tag.first);   // dimension 0/1/2/3
        int tag = dim_tag.second;                              // physical tag in gmsh
        std::string name;                                      // discription in gmsh
        gmsh::model::getPhysicalName(dim, tag, name);
        
        // generate next key for mesh.element_group
        mesh.dim_keys[dim].id++;
        Key gmsh_key = mesh.dim_keys[dim];
        
        mesh.element_group[gmsh_key];
        mesh.element_group_description[gmsh_key] = name;

        Logger::mesh_entity(dim, tag, mesh.dim_keys[dim].id, name);

        std::vector<int> entity_tags;
        gmsh::model::getEntitiesForPhysicalGroup(dim, tag, entity_tags);

        std::vector<int> element_types;
        std::vector<std::vector<std::size_t>> element_tags;
        std::vector<std::vector<std::size_t>> node_tags;
        for (int entity_tag : entity_tags) {
            gmsh::model::mesh::getElements(element_types, element_tags, node_tags, dim, entity_tag);
        }
    }
    
    std::vector<int> entityTags;
    gmsh::model::getEntitiesForPhysicalGroup(2, 10, entityTags);

    // 2. For each of those entities, get the elements
    for (int entityTag : entityTags) {
        std::vector<int> elementTypes;
        std::vector<std::vector<std::size_t>> elementTags;
        std::vector<std::vector<std::size_t>> nodeTags;
        
        // This retrieves all elements (triangles, quads, etc.) for that entity
        gmsh::model::mesh::getElements(elementTypes, elementTags, nodeTags, 2, entityTag);
        
        // Now 'elementTags' contains the IDs of all triangles in the "Interface"
    }

    gmsh::finalize();
    //std::cout<<mesh.n_element<<std::endl;
    return mesh;
#else
    throw std::runtime_error("Gmsh support not compiled!");
#endif
}