#include "entity/mesh/mesh_parser.h"
#include "entity/mesh/e_tetrahedron.h"
#include "entity/mesh/e_triangle.h"

#include <map>
#include <algorithm>
#include <filesystem>



Mesh_Parser::Mesh_Parser(Mesh_Format format):format_(format)
{

}



/**
 * @brief Converts a Gmsh element type ID into internal mesh properties.
 * * This function maps the standard Gmsh element identifiers (found in the MSH 
 * file format or returned by gmsh::model::mesh::getElements) to the internal 
 * Type enum, the polynomial order, and the total number of nodes per element.
 * 
 * 
 * @param gmsh_type The integer ID provided by the Gmsh API (e.g., 2 for a 3-node triangle).
 * @return std::tuple<Type, int, int> A tuple containing:
 * - [0]: Internal Type enum (e.g., Type::TRIANGLE).
 * - [1]: Polynomial order (1 for linear, 2 for quadratic, etc.).
 * - [2]: Number of nodes per element (used as a stride for the node_tags vector).
 * * @throws std::invalid_argument If the gmsh_type does not map to a supported internal shape.
 * * @note Current support is limited to 1st-order linear elements:
 * - Type 1: 2-node line
 * - Type 2: 3-node triangle
 * - Type 4: 4-node tetrahedron
 * - Type 15: 1-node point
 */
std::tuple<Type, int, int> Mesh_Parser::convert_Type(int gmsh_type) {
    switch (gmsh_type) {
        case 1:  return {Type::EDGE,        1, 2}; // 2-node line
        case 2:  return {Type::TRIANGLE,    1, 3}; // 3-node triangle
        case 4:  return {Type::TETRAHEDRON, 1, 4}; // 4-node tetrahedron
        case 15: return {Type::NODE,        1, 1}; // 1-node point
        default:
            // Handle unsupported shapes (Quads, Hexahedra, etc.)
            throw std::invalid_argument("Unsupported Gmsh element type: " + std::to_string(gmsh_type));
    }
}

Element* Mesh_Parser::create_element(Type element_type, std::vector<std::size_t> node_idx, size_t property_id, int o)
{
    switch (element_type) 
    {
        case Type::TRIANGLE:     return new Triangle(node_idx, property_id, 1);
        case Type::TETRAHEDRON:  return new Tetrahedron(node_idx, property_id, 1);
        default: return nullptr;
    }
}




Mesh Mesh_Parser::load_mesh(const std::string& filename)
{
    std::string ext = std::filesystem::path(filename).extension().string();
    switch (format_) {
        case Mesh_Format::GMSH:
            if (ext == ".msh" || ext == ".geo")
            {
                return load_gmsh(filename);
            } else {
                throw std::runtime_error("Error: Gmsh does not support " + ext + " format for file: " + filename);
            }
        default:
            throw std::runtime_error("Mesh format " + ext + " is not supported yet.");;
    }
}




Mesh Mesh_Parser::load_gmsh(const std::string& filename)
{
#ifdef LOAD_GMSH
    gmsh::initialize();
    gmsh::option::setNumber("General.Verbosity", 1);
    gmsh::open(filename);

    Logger::info("Load mesh: " + filename);

    Mesh mesh;
    mesh.dim_ = gmsh::model::getDimension();

    // ---- Nodes ----
    std::vector<size_t> node_tags;
    std::vector<double> coords;
    std::vector<double> parametric; // unused

    //gmsh::model::mesh::generate(mesh.dim_);
    gmsh::model::mesh::getNodes(node_tags, coords, parametric);
    mesh.n_node = node_tags.size();


    // Store node coordinates indexed by 0-based index.
    // Gmsh returns nodes in node_tags order, which may not be contiguous,
    // so we use the tag_to_idx mapping.
    mesh.nodes.resize(mesh.n_node);
    for (size_t i = 0; i < node_tags.size(); ++i) 
    {
        //size_t idx = tag_to_idx[node_tags[i]];
        mesh.nodes[node_tags[i]-1].x = coords[3 * i];
        mesh.nodes[node_tags[i]-1].y = coords[3 * i + 1];
        mesh.nodes[node_tags[i]-1].z = coords[3 * i + 2];
    }

    // create key of element groups generated by gmsh file
    gmsh::vectorpair                   physicalGroups_dim_tag;
    std::map<std::pair<int, int>, Key> physicalGroups_to_key;
    gmsh::model::getPhysicalGroups(physicalGroups_dim_tag);

    Logger::info("Node number: " + std::to_string(mesh.n_node));


    Logger::info("Physical groups: Load elements...");
    for(std::pair<int,int> &dim_tag : physicalGroups_dim_tag)
    {
        uint32_t dim = static_cast<uint32_t>(dim_tag.first);   // dimension 0/1/2/3
        int tag = dim_tag.second;                              // physical tag in gmsh
        std::string name;                                      // discription in gmsh
        gmsh::model::getPhysicalName(dim, tag, name);


        // generate next key for mesh.element_group
        mesh.dim_keys[dim].id++;
        Key gmsh_key = mesh.dim_keys[dim];
        
        mesh.element_group[gmsh_key];
        mesh.element_group_description[gmsh_key] = name;
        

        // get entity tags from physical groups
        std::vector<int> entity_tags;
        gmsh::model::getEntitiesForPhysicalGroup(dim, tag, entity_tags);

        // get all elements from entity
        
        for (int entity_tag : entity_tags)
        {   
            std::vector<int> element_types;
            std::vector<std::vector<std::size_t>> element_tags;
            std::vector<std::vector<std::size_t>> node_tags;
            // element_types and element_tags should have same size
            gmsh::model::mesh::getElements(element_types, element_tags, node_tags, dim, entity_tag);
            
            // one entity can be made of different type of elements, element_tags.size() is number of different shapes
            for (size_t i = 0; i < element_tags.size(); ++i) 
            {   
                auto [type, order, n_node] = convert_Type(element_types[i]);

                size_t n_elements = element_tags[i].size();
                for (size_t j=0; j<n_elements; ++j)
                {   
                    size_t element_id = element_tags[i][j];
                    // TODO encode element_id into Element class
                    // create vector<Element> of all elements,
                    // then element group only reference from their?
                    //   -> avoid using pointer soup!
                    auto startIt = node_tags[i].begin() + (j * n_node);
                    auto endIt   = startIt + n_node;
                    
                    std::vector<std::size_t> element_node_tags(startIt, endIt);

                    Element * element = create_element(type, element_node_tags, gmsh_key.id, order);
                    mesh.element_group[gmsh_key].push_back(element);
                }
            }
        }

        

        Logger::mesh_entity(dim, tag, mesh.dim_keys[dim].id, mesh.element_group[gmsh_key].size(), name);
    }
    
    std::vector<int> entityTags;
    gmsh::model::getEntitiesForPhysicalGroup(2, 10, entityTags);

    // 2. For each of those entities, get the elements
    for (int entityTag : entityTags) {
        std::vector<int> elementTypes;
        std::vector<std::vector<std::size_t>> elementTags;
        std::vector<std::vector<std::size_t>> nodeTags;
        
        // This retrieves all elements (triangles, quads, etc.) for that entity
        gmsh::model::mesh::getElements(elementTypes, elementTags, nodeTags, 2, entityTag);
        
        // Now 'elementTags' contains the IDs of all triangles in the "Interface"
    }

    gmsh::finalize();
    //std::cout<<mesh.n_element<<std::endl;
    return mesh;
#else
    throw std::runtime_error("Gmsh support not compiled!");
#endif
}